### ISSUE TITLE
Script.before() and after() when using mid-level API

### ISSUE THREAD

**Issue by Braunmann** [golemfactory/yajsapi#493]
during preview program it came out that user had problem with upload/download of files.

** Ticket Request

Hi, I'm working on the task 5 on JS preview program. I'm stuck on the part where I need to upload and download the files, while using core js API. This is the code snippet I'm currently using:
```ts
    import { GftpStorageProvider } from "yajsapi/dist/storage/index.js"
    import { UploadFile, DownloadFile } from "yajsapi/dist/script/index.js";

    const gftpStorageProvider = new GftpStorageProvider(logger);
    await gftpStorageProvider.init();
    const script = Script.create([
        new Deploy(),
        new Start(),
        new UploadFile(gftpStorageProvider, 'restaurant_anim_test.zip', '/golem/input/restaurant_anim_test.zip'),
        new Run("/bin/sh", ["-c", "unzip /golem/input/restaurant_anim_test.zip"]),
        new Run("/bin/sh", ["-c", "date +%s"]),
        new Run("/bin/sh", ["-c", "blender -b restaurant_anim_test/rain_restaurant.blend -E CYCLES -o /golem/output/rain_####.png -f 1"]),
        new Run("/bin/sh", ["-c", "date +%s"]),
        new DownloadFile(gftpStorageProvider, '/golem/output/rain_0001.png', 'rain_0001.png'),
    ]);
```

But, I'm getting this error:
```
2023-05-24T13:01:18.143Z [error] Error: Request failed with status code 400
Error: Bad request: Error("missing field `from`", line: 1, column: 96)
    at Activity.execute (file:///home/ojuswi/Documents/repos/golem-js-preview-program/tasks/5-best-provider-selection/node_modules/yajsapi/dist/activity/activity.js:41:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runJob (file:///home/ojuswi/Documents/repos/golem-js-preview-program/tasks/5-best-provider-selection/src/harvest.js:41:26)
    at async main (file:///home/ojuswi/Documents/repos/golem-js-preview-program/tasks/5-best-provider-selection/src/harvest.js:106:24)
```

**Comment by Braunmann** [comment]
After investing, I came to the conclusion that it is required to call the method `before()` and `after()` on object type of `Script` returned by static method `Script.create()`.

This problem happens when you are using Mid-Level API.

My proposed solution for this moment was to explicit call both methods before and after execute script on activity, like: 
```ts
await script.before(); // <- this line
const exeScript = script.getExeScriptRequest();
const streamResult = await activity.execute(exeScript);
await script.after(); // <- this line
```

*** TBD
We need to discuss if it is right way to call explict the `before()` and `after()` methods. If yes, we have to document this.

**Comment by mgordel** [comment]
Yes, at mid-level, `before` and `after` calls must be explicit. The hello world mid-level example should be fixed and described in the documentation.
